# Generated by Django 6.0.1 on 2026-02-25 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('referrer_name', models.CharField(max_length=255, verbose_name='Referrer Name')),
                ('referrer_email', models.EmailField(blank=True, max_length=254, verbose_name='Referrer Email')),
                ('referred_name', models.CharField(max_length=255, verbose_name='Referred Name')),
                ('referred_email', models.EmailField(blank=True, max_length=254, verbose_name='Referred Email')),
                ('referral_code', models.CharField(blank=True, max_length=50, verbose_name='Referral Code')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('converted', 'Converted'), ('rewarded', 'Rewarded'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Status')),
                ('reward_given', models.BooleanField(default=False, verbose_name='Reward Given')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'db_table': 'referrals_referral',
                'abstract': False,
            },
        ),
    ]
